module.exports = {
  caseType: 'approved_robotic_choreography_run',
  initialState: 'run_registered',
  states: ['run_registered','inputs_versioned','sandbox_queued','sandbox_evaluated','safety_review','operator_approved','execution_observed','execution_failed','rollback_verified','closed'],
  createRoles: ['developer','fleet_operator'],
  assessmentRoles: ['developer','safety_reviewer','reliability_reviewer'],
  auditRoles: ['fleet_operator','safety_reviewer','auditor'],
  connectorRoles: ['integration_operator','fleet_operator'],
  evidenceKinds: ['repository_revision','ci_receipt','task_manifest','fleet_snapshot','zone_snapshot','telemetry_manifest','sandbox_artifact','evaluation_report','safety_report','approval_record','execution_receipt','failure_record','rollback_record','cost_latency_report'],
  requiredSignals: ['repositoryVersion','workflowVersion','fleetVersion','zoneVersion','telemetryVersion','policyVersion','safetyLimitsVerified','correctnessScore','reliabilityScore','p95LatencyMs','costPerRun','regressionDelta','concurrencyRecoveryScore'],
  professionalBoundary: 'The workflow records versioned simulations and human approvals only. It cannot command robots, PLCs, safety systems, or other hardware.',
  connectors: [
    { name:'repository', purpose:'signed revision receipts' },
    { name:'ci_cd', purpose:'build and evaluation receipts' },
    { name:'model_provider', purpose:'sandbox suggestion receipts only' },
    { name:'telemetry', purpose:'read-only versioned telemetry manifests' },
    { name:'secret_manager', purpose:'credential references, never secret values' },
    { name:'artifact_store', purpose:'immutable evaluation artifact pointers' },
    { name:'ticketing', purpose:'failure and approval receipts' },
    { name:'device_gateway', purpose:'read-only observation receipts; commands prohibited' },
  ],
  transitions: [
    { from:'run_registered',action:'lock_inputs',to:'inputs_versioned',roles:['developer'],requiresEvidence:true },
    { from:'inputs_versioned',action:'queue_sandbox',to:'sandbox_queued',roles:['developer','integration_operator'],requiresEvidence:true },
    { from:'sandbox_queued',action:'record_evaluation',to:'sandbox_evaluated',roles:['reliability_reviewer','integration_operator'],requiresEvidence:true },
    { from:'sandbox_evaluated',action:'submit_safety_review',to:'safety_review',roles:['safety_reviewer'],requiresEvidence:true,dualControl:true },
    { from:'safety_review',action:'approve_observation',to:'operator_approved',roles:['fleet_operator','safety_reviewer'],requiresEvidence:true,dualControl:true },
    { from:'operator_approved',action:'record_observation',to:'execution_observed',roles:['fleet_operator','integration_operator'],requiresEvidence:true,dualControl:true },
    { from:'operator_approved',action:'record_failure',to:'execution_failed',roles:['fleet_operator','integration_operator'],requiresEvidence:true },
    { from:'execution_failed',action:'verify_rollback',to:'rollback_verified',roles:['safety_reviewer','fleet_operator'],requiresEvidence:true,dualControl:true },
    { from:'execution_observed',action:'close_run',to:'closed',roles:['fleet_operator','auditor'],requiresEvidence:true },
    { from:'rollback_verified',action:'close_run',to:'closed',roles:['fleet_operator','auditor'],requiresEvidence:true },
  ],
  acceptedFixture: {repositoryVersion:'git-a1',workflowVersion:'wf1',fleetVersion:'f1',zoneVersion:'z1',telemetryVersion:'t1',policyVersion:'p1',safetyLimitsVerified:true,correctnessScore:0.99,reliabilityScore:0.995,p95LatencyMs:800,costPerRun:1.2,regressionDelta:0.01,concurrencyRecoveryScore:0.98},
  rejectedFixture: {repositoryVersion:'git-a1',workflowVersion:'wf1',fleetVersion:'f1',zoneVersion:'z1',telemetryVersion:'t1',policyVersion:'p1',safetyLimitsVerified:false,correctnessScore:0.99,reliabilityScore:0.995,p95LatencyMs:800,costPerRun:1.2,regressionDelta:0.01,concurrencyRecoveryScore:0.98},
  readyDisposition:'independent_operator_review_required',
  holdDisposition:'safety_reliability_or_regression_hold',
  decisionField:'executionCommand',
  assess:(x)=>{const correctness=Number(x.correctnessScore),reliability=Number(x.reliabilityScore),latency=Number(x.p95LatencyMs),cost=Number(x.costPerRun),regression=Number(x.regressionDelta),recovery=Number(x.concurrencyRecoveryScore);const ready=x.safetyLimitsVerified===true&&correctness>=0.98&&reliability>=0.99&&latency<=1000&&cost<=2&&regression<=0.02&&recovery>=0.95;return{disposition:ready?'independent_operator_review_required':'safety_reliability_or_regression_hold',executionCommand:null,metrics:{correctness,reliability,latency,cost,regression,recovery},versions:{repository:x.repositoryVersion,workflow:x.workflowVersion,fleet:x.fleetVersion,zone:x.zoneVersion,telemetry:x.telemetryVersion}};},
};
